version: 2.1
orbs:
    node: circleci/node@3.0.0
jobs:
    test:
        steps:
            - checkout
            - run: npm run test
    build:
        steps:
            - checkout
            - run: npm run start
workflows:
    node-tests:
        jobs:
            - test
