export const FETCH_PROGRAMS = "FETCH_PROGRAMS";
export const FETCH_FILTERED_PROGRAMS = "FETCH_FILTERED_PROGRAMS";
export const FETCH_FILTERS = "FETCH_FILTERS";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const FETCH_PROGRAMS_FAIL = "FETCH_PROGRAMS_FAIL";
export const FETCH_PROGRAMS_SUCCESS = "FETCH_PROGRAMS_SUCCESS";
